production:
  adapter: em_postgresql
  encoding: unicode
  database: api_fiberpool_rails_development
  pool: 25
  username: postgres
  password: postgres

development:
  adapter: em_postgresql
  encoding: unicode
  database: api_fiberpool_rails_development
  pool: 25
  username: postgres
  password: postgres

test:
  adapter: em_postgresql
  encoding: unicode
  database: api_fiberpool_rails_test
  pool: 25
  username: postgres
  password: postgres

